### ISSUE TITLE
Issues specifying daphne arguments

### ISSUE THREAD

**Issue by aduquehd** [sivulich/mqttasgi#19]
Hi.

I run a project using daphne using the following command: `daphne -b 0.0.0.0 config.asgi:application`.

Is possible to specify something like that in the `mqttasgi` command ?

`mqttasgi -H localhost -p 1883 my_application.asgi:application`

**Comment by sivulich** [comment]
Hi!

Mqttasgi is a protocol server that replaces Daphne or Uvicorn. You need to
run your project with the mqttasgi command 😊

Kind regards,
S
