### ISSUE TITLE
CONNECTION_ERROR

### ISSUE THREAD

**Issue by medmile** [sivulich/mqttasgi#24]
Hello, i have error.

django==3.0
channels==3.0.5

from mqttasgi.consumers import MqttConsumer
class StepMqttConsumer(MqttConsumer):

    async def connect(self):
        await self.subscribe('my/testing/topic', 2)
        
    async def receive(self, mqtt_message):
        print('Received a message at topic:', mqtt_message['topic'])
        print('With payload', mqtt_message['payload'])
        print('And QOS:', mqtt_message['qos'])
        pass

    async def disconnect(self):
        await self.unsubscribe('my/testing/topic')

application = ProtocolTypeRouter({
    'http': django_asgi_app,
    'websocket': AllowedHostsOriginValidator(
        #AuthMiddlewareStack(
        JwtAuthMiddlewareStack(  
            URLRouter(
                [path("ws/chat/<room_name>/", ChatConsumer.as_asgi()),
                path("ws/tasks/", TasksConsumer.as_asgi()),]
            )
        )
    ),
    'mqtt': StepMqttConsumer.as_asgi(),
})

medmike@wstep:~/step/step_api$ /home/medmike/step/venv/bin/mqttasgi -H localhost -p 1883 step_api.asgi:application
2023-12-22 17:02:51,716 WARNING  MQTTASGI Received signal CONNECTION_ERROR, terminating
2023-12-22 17:02:51,716 WARNING  MQTTASGI Waiting for all applications to close

Can you help me?

**Comment by sivulich** [comment]
Hi @medmile, sounds like your broker is refusing the connection, if using mosquitto, do you have the following configurations?
```
allow_anonymous true
listener 1883 0.0.0.0
```
